spring:  
  cloud: 
    stream: 
      function:
        definition: remotePacketSupplier;remotePacketConsumer
      bindings: 
        remotePacketSupplier-out-0: 
          destination: timplus-ng-remote-packet

        remotePacketConsumer-in-0: 
          destination: timplus-ng-remote-packet
          consumer:
            concurrency: 10    
            maxAttempts: 4
            backOffInitialInterval: 15000
            backOffMaxInterval: 60000  