spring:
  flyway:
    locations: classpath:db/migration/{vendor}

  datasource:
    #url: "jdbc:hsqldb:embedded-db/openfire"
    #username: sa
    #password: 
    url: "jdbc:mysql://localhost:3306/nhind"
    username: nhind
    password: nhind    

  integration.jdbc.initializeSchema: ALWAYS

timplus:
  domain: domain.com
  adminUsername: gm2552@domain.com
  adminPassword: 1kingpuff
  
  monitor.condition.generalConditionTimeout: 5000

  filetransfer.proxy.host: xmppserver.cernerdirectsupport.com
  vcard.allowClientSet: false
  secandtrust.crl.ignoreCLRChecking: true
  secandtrust.crl.fileCahceLoc: 